# Generated by Django 4.2 on 2025-02-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PATIENT', 'Patient'), ('DOCTOR', 'Doctor')], default='PATIENT', max_length=10),
        ),
    ]
